name: Build build sing-box-ruleset
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/build-geox.yml"
      - ".github/workflows/build-clash-ruleset.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@master

      - name: Download and unzip `sing-box core`
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
          mkdir -p ./ruleset/sing-box/ ./tmp/
          sing_box_version=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep 'tag_name' | sed 's/.*v//g' | sed 's/",$//g')
          wget "https://github.com/SagerNet/sing-box/releases/download/v${sing_box_version}/sing-box-${sing_box_version}-linux-amd64.tar.gz" -O - | tar -zxf - -C ./tmp/
          mv -f ./tmp/sing-box-${sing_box_version}-linux-amd64/sing-box ./ruleset/sing-box/

      - name: Download and unzip `mosdns`
        run: |
          wget -P ./tmp/ "https://github.com/IrineSistiana/mosdns/releases/download/v4.5.3/mosdns-linux-amd64.zip"
          unzip -o "./tmp/mosdns-linux-amd64.zip" -d ./tmp/
          mv -f ./tmp/mosdns ./ruleset/sing-box/

      - name: Convert geo to sing-rule-set
        env:
          NO_SKIP: true
        run: |
          cp -f ./geox/sing-box/geosite-all.db ./geox/clash/geoip-all.dat ./ruleset/sing-box/
          wget -P ./ruleset/sing-box/ https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/master/resouces/convert.sh
          cd ./ruleset/sing-box/
          chmod +x mosdns sing-box convert.sh
          ./convert.sh
          rm -rf ../../tmp* mosdns sing-box convert.sh geosite-all.db geoip-all.dat LICENSE README.md config.yaml

      - name: Commit and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add . && git commit -m "更新于 ${update_version}" || exit 0
          git push -f

      - name: Purge jsDelivr CDN
        run: |
          cd ./ruleset/sing-box/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@master/ruleset/sing-box/${file}"
          done
