name: Batch Delete Tags
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Delete Tags
      run: |
        git tag -l | xargs git tag -d
        git fetch --prune --tags
        git push origin --delete $(git tag -l)
